# Base image
FROM python:3.11-slim

# Working directory
WORKDIR /app

# Copy all files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Frontend port
EXPOSE 80

# Run Frontend app
CMD ["python", "frontend_travel.py"]
